cart/urls.py
from django.urls import path

from .views import CartSummary, UpdateCart, UsePromoCode

urlpatterns = [
    path("", CartSummary.as_view(), name="cart_summary"),
    path("update-cart/", UpdateCart.as_view(), name="cart_update"),
    path("use-promo-code/", UsePromoCode.as_view(), name="use_promo_code"),
]

megano_shop/urls.py
import mptt_urls
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path

from .models import Category
from .views import (
    AddToCompareList,
    CompareListView,
    ItemListView,
    OrderDeliveryInfoView,
    OrderPaymentTypeView,
    OrderSubmitView,
    OrderUserInfoView,
    ProductDetailView,
    ReviewAddView,
    ReviewsListView,
    add_to_viewed,
    delete_from_compare_list,
    delete_from_viewed,
    index_page,
    is_viewed,
    order_detail,
    sales_list,
    seller_detail,
    viewed_goods,
    viewed_goods_number,
)

urlpatterns = [
    path("", index_page, name="index"),
    re_path(
        r"category/(?P<path>.*)",
        mptt_urls.view(model=Category, view=ItemListView.as_view()),
        name="filtered_category",
    ),
    path("compare/", CompareListView.as_view(), name="compare_list"),
    path("add_to_compare/", AddToCompareList.as_view(), name="add_to_compare"),
    path(
        "delete_from_compare/<slug:slug>",
        delete_from_compare_list,
        name="delete_from_compare_list",
    ),
    path("cart/get_user_info", OrderUserInfoView.as_view(), name="get_user_info"),
    path(
        "cart/get_delivery_info",
        OrderDeliveryInfoView.as_view(),
        name="get_delivery_info",
    ),
    path(
        "cart/get_payment_type_info",
        OrderPaymentTypeView.as_view(),
        name="get_payment_type",
    ),
    path("cart/submit_order", OrderSubmitView.as_view(), name="submit_order"),
    path("sales/", sales_list, name="sales_list"),
    path("order/<str:order_id>", order_detail, name="order_detail"),
    path(
        "catalog/<int:goods_id>/reviews/",
        ReviewsListView.as_view(),
        name="reviews_list",
    ),
    path(
        "catalog/<int:goods_id>/add_review/", ReviewAddView.as_view(), name="review_add"
    ),
    path("catalog/<int:pk>/detail", ProductDetailView.as_view(), name="product_detail"),
    path("catalog/<int:user_id>/views/", viewed_goods, name="viewed_goods"),
    path(
        "catalog/<int:user_id>-<int:goods_id>/add_to_viewed/",
        add_to_viewed,
        name="add_to_viewed",
    ),
    path(
        "catalog/<int:user_id>/viewed_number/",
        viewed_goods_number,
        name="viewed_goods_number",
    ),
    path(
        "catalog/<int:user_id>-<int:goods_id>/delete_from_viewed/",
        delete_from_viewed,
        name="delete_from_viewed",
    ),
    path(
        "catalog/<int:user_id>-<int:goods_id>/is_viewed/", is_viewed, name="is_viewed"
    ),
    path("seller/<str:seller_username>/", seller_detail, name="seller"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python_django_team17/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("acc/", include("account.urls")),
    path("", include("megano_shop.urls")),
    path("payment/", include("payment.urls")),
    path("cart/", include("cart.urls")),
    path("i18n", include("django.conf.urls.i18n")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

megano_shop/models.py
from decimal import Decimal

from constance import config
from django.contrib import admin
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    """Model for Category with nasted tree"""

    title = models.CharField(max_length=60, unique=True, verbose_name=_("Category"))
    parent = TreeForeignKey(
        "self",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="children",
        verbose_name=_("Parent category"),
    )
    slug = models.SlugField()
    is_active = models.BooleanField(verbose_name=_("Is active"), default=False)
    icon = models.ImageField(
        upload_to="img/category_icons", verbose_name=_("Icon"), blank=True, null=True
    )
    discount = models.ManyToManyField(
        to="Discounts", blank=True, verbose_name=_("Discount")
    )

    class MPTTMeta:
        order_insertion_by = ["title"]

    class Meta:
        unique_together = [["parent", "slug"]]
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    @admin.display(description="Icon_preview")
    def icon_prev(self):
        return mark_safe(f'<img src="{self.icon.url}" width="100"/>')

    def get_absolute_url(self):
        return reverse("filtered_category", kwargs={"path": self.get_path()})

    def __str__(self):
        return self.title


class Tags(models.Model):
    name = models.CharField(max_length=50, verbose_name=_("Tag"))

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")

    def __str__(self):
        return self.name


class Images(models.Model):
    image = models.ImageField(upload_to="items", blank=True, verbose_name=_("Image"))

    class Meta:
        verbose_name = _("Image")
        verbose_name_plural = _("Images")


class Item(models.Model):
    """Model for Item"""

    STATUS_CHOICES = [
        ("a", "Active"),
        ("i", "Inactive"),
    ]

    category = TreeForeignKey(
        Category,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="item_category",
        verbose_name=_("Category"),
    )
    slug = models.SlugField(verbose_name=_("slug"))
    tag = models.ManyToManyField(
        Tags, blank=True, related_name="tag_item", verbose_name=_("Tag")
    )
    title = models.CharField(max_length=100, verbose_name=_("Title"))
    main_image = models.ImageField(
        upload_to="img/item_images/%Y/%m/%d/", blank=True, verbose_name=_("Main image")
    )
    discount = models.ManyToManyField(
        "Discounts", blank=True, related_name="item", verbose_name=_("Discount")
    )
    images = models.ManyToManyField(Images, blank=True, verbose_name=_("Images"))
    description = models.TextField(max_length=1000, verbose_name=_("Description"))
    status = models.CharField(
        max_length=1, choices=STATUS_CHOICES, default="a", verbose_name=_("Status")
    )
    specifications = models.JSONField(
        verbose_name=_("Specifications"), blank=True, null=True
    )
    count_view = models.IntegerField(default=0, verbose_name=_("count view"))

    class Meta:
        verbose_name = _("Item")
        verbose_name_plural = _("Items")

    def get_absolute_url(self):
        return reverse("items_list", args=[str(self.slug)])

    def __str__(self):
        return self.title

    def __repr__(self):
        return self.title


class Banner(models.Model):
    """Model for Banners"""

    image = models.ImageField(
        upload_to="images/%Y/%m/%d/", blank=True, verbose_name=_("Banner image")
    )
    link = models.URLField(max_length=200, verbose_name=_("URL"))
    title = models.CharField(max_length=17, verbose_name=_("Title"))
    description = models.TextField(max_length=300, verbose_name=_("Description"))
    is_active = models.BooleanField(default=False, verbose_name=_("Status"))

    class Meta:
        # verbose_name = "Banner"
        verbose_name_plural = _("Banners")

    def get_absolute_url(self):
        pass

    def __str__(self):
        return self.link


class Reviews(models.Model):
    """Reviews model"""

    created_on = models.DateTimeField(
        auto_now_add=True, verbose_name=_("Creation date")
    )
    edited_on = models.DateTimeField(auto_now=True, verbose_name=_("Updating date"))
    user = models.ForeignKey(
        to=User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        verbose_name=_("User"),
        related_name="review_user",
    )
    item = models.ForeignKey(
        to=Item,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        verbose_name=_("Item"),
        related_name="review_item",
    )
    content = models.TextField(
        max_length=3000, blank=True, verbose_name=_("Review text")
    )

    class Meta:
        verbose_name = _("Review")
        verbose_name_plural = _("Reviews")

    def __str__(self):
        if User.is_authenticated:
            return str(self.user)
        else:
            return _("Guest")


class Discounts(models.Model):
    """Model for Discount"""

    TYPE = [
        ("p", _("Promo code")),
        ("d", _("Discount")),
    ]

    AMOUNT_CHOICE = [("cashed", _("Fixed amount")), ("percentage", _("Percentage"))]

    title = models.CharField(max_length=200, verbose_name=_("Title"))
    description = models.TextField(verbose_name=_("Description"))
    image = models.ImageField(
        upload_to="images/%Y/%m/%d/promo/", blank=True, verbose_name=_("Promo image")
    )
    discount_weight = models.PositiveIntegerField(
        default=0,
        validators=[MaxValueValidator(10), MinValueValidator(1)],
        verbose_name=_("Discount weight"),
    )
    discount_type = models.CharField(
        max_length=1, choices=TYPE, default="d", verbose_name=_("Discount type")
    )
    amount_type = models.CharField(
        max_length=10,
        choices=AMOUNT_CHOICE,
        default="cashed",
        verbose_name=_("Amount type"),
    )
    amount = models.PositiveIntegerField(
        default=0, verbose_name=_("Discount"), blank=True, null=True
    )
    promo_code = models.CharField(
        max_length=50, verbose_name=_("Promo code text"), blank=True, null=True
    )
    items_qty = models.PositiveIntegerField(
        default=0, validators=[MaxValueValidator(100), MinValueValidator(0)]
    )
    starts_on = models.DateTimeField(blank=True, verbose_name=_("Starts on"), null=True)
    ends_on = models.DateTimeField(blank=True, verbose_name=_("Ends on"), null=True)
    is_active = models.BooleanField(default=False, verbose_name=_("Activity"))

    class Meta:
        verbose_name = _("Discount")
        verbose_name_plural = _("Discounts")

    def __str__(self):
        return self.title


class AppliedDiscounts(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        verbose_name=_("User"),
        related_name="user_applied_discount",
    )
    discount = models.ForeignKey(
        to=Discounts,
        on_delete=models.CASCADE,
        verbose_name=_("Discount"),
        related_name="applied_discount",
    )

    class Meta:
        db_table = "megano_shop_applied_discounts"
        verbose_name = _("Applied Discount")
        verbose_name_plural = _("Applied Discounts")


class Stock(models.Model):
    """Model for Stock"""

    item = models.ForeignKey(
        Item,
        blank=True,
        on_delete=models.CASCADE,
        related_name="stock_item",
        verbose_name=_("Item"),
    )
    seller = models.ForeignKey(
        User, blank=True, on_delete=models.PROTECT, verbose_name=_("Seller")
    )
    quantity = models.PositiveIntegerField(default=0, verbose_name=_("Quantity"))
    discount = models.ForeignKey(
        Discounts,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_("Discount"),
    )
    price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0, verbose_name=_("Price")
    )
    count_view = models.IntegerField(default=0, verbose_name=_("count view"))
    created_on = models.DateTimeField(auto_now_add=True, verbose_name=_("Created on"))

    class Meta:
        verbose_name = _("Stock")
        verbose_name_plural = _("Stocks")

    def __str__(self):
        return self.seller.username

    @property
    def get_category(self):
        return self.item.category


class Order(models.Model):
    ORDER_STATUS_CHOICES = [
        ("o", _("Open")),
        ("c", _("Closed")),
    ]
    PAYMENT_STATUS_CHOICES = [
        ("p", _("Payed")),
        ("u", _("Not paid")),
    ]
    DELIVERY_CHOICE = (
        ("ordinary", _("Ordinary delivery")),
        ("express", _("Express delivery")),
    )
    PAYMENT_CHOICE = (
        ("online_card", _("Online")),
        ("online_account", _("Online from random person's account")),
    )
    order_number = models.CharField(
        max_length=6, unique=True, verbose_name=_("Order number")
    )
    buyer = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name="order_buyer",
        verbose_name=_("Customer"),
    )
    total_price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0, verbose_name=_("Total amount")
    )
    payment_method = models.CharField(
        max_length=60,
        choices=PAYMENT_CHOICE,
        default="online_card",
        verbose_name=_("Payment method"),
    )
    shipping_type = models.CharField(
        max_length=250,
        choices=DELIVERY_CHOICE,
        default="ordinary",
        verbose_name=_("Delivery"),
    )
    payment_status = models.CharField(
        max_length=60,
        choices=PAYMENT_STATUS_CHOICES,
        default="u",

megano_shop/templates/megano_shop/catalog.html
{% extends 'base.html' %}
{% load static %}
{% load cache %}
{% load card_tags %}
{% load i18n %}

{% block title %}{% endblock title %}

{% block content %}

    <div class="Middle Middle_top">
        <div class="Middle-top">
            <div class="wrap">
                <div class="Middle-header">
                    <h1 class="Middle-title">{% trans "Catalog Megano" %}
                    </h1>
                    <ul class="breadcrumbs Middle-breadcrumbs">
                        <li class="breadcrumbs-item"><a href="index.html">home</a>
                        </li>
                        <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% trans "Catalog" %}</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="Section Section_column Section_columnLeft">
            <div class="wrap">
                <div class="Section-column">
                    <div class="Section-columnSection">
                        <header class="Section-header">
                            <strong class="Section-title">{% trans "Filter" %}
                            </strong>
                        </header>
                        <div class="Section-columnContent">
                            <form class="form" method="get">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button style="background-color: #1d459b; color: #ffffcc; border-radius: 8px; width: 10rem"
                                        type="submit">{% trans "Filter" %}</button>
                            </form>
                        </div>
                    </div>
                    <div class="Section-columnSection">
                        <header class="Section-header">
                            <strong class="Section-title">{% trans "Popular tags" %}
                            </strong>
                        </header>
                        <div class="Section-columnContent">
                            <div class="buttons"><a class="btn btn_default btn_sm" href="#">{% trans "Video" %}</a><a
                                    class="btn btn_default btn_sm" href="#">{% trans "Development" %}</a><a
                                    class="btn btn_default btn_sm"
                                    href="#">{% trans "Gaming" %}</a><a
                                    class="btn btn_default btn_sm" href="#">Asus</a><a class="btn btn_default btn_sm"
                                                                                       href="#">{% trans "Development" %}</a><a
                                    class="btn btn_default btn_sm" href="#">{% trans "Video" %}</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="Section-content">
                    <div class="Sort">


                    </div>
                    <div class="Cards">
                        {% for item in page_obj %}
                            {% include "megano_shop/Includes/item_card.html" %}
                        {% endfor %}
                    </div>
                    <div class="Pagination">
                        <div class="Pagination-ins">
                            {% if page_obj.has_other_pages %}
                                {% if page_obj.has_previous %}
                                    <a class="Pagination-element Pagination-element_prev"
                                       href="?{% url_replace 'page' page_obj.previous_page_number %}">
                                        <img src="{% static "assets/img/icons/prevPagination.svg" %}"
                                             alt="prevPagination.svg"/>
                                    </a>
                                {% endif %}
                                {% for p in page_obj.paginator.page_range %}
                                    {% if page_obj.number == p %}
                                        <span class="Pagination-element Pagination-element_current">{{ p }}</span>
                                        {#                                {% else %}#}
                                        {#                                    <a class="Pagination-element" href="?page={{ p }}">#}
                                        {#                                        <span class="Pagination-text">{{ p }}</span>#}
                                        {#                                    </a>#}
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <a class="Pagination-element Pagination-element_prev"
                                       href="?{% url_replace 'page' page_obj.next_page_number %}">
                                        <img src="{% static "assets/img/icons/nextPagination.svg" %}"
                                             alt="nextPagination.svg"/>
                                    </a>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

megano_shop/templates/megano_shop/category_list.html
{% load mptt_tags %}
{% load static %}
{% load i18n %}

<div class="Header-categories">
    <div class="CategoriesButton">
        <div class="CategoriesButton-title">
            <div class="CategoriesButton-icon"><img
                    src={% static "megano_shop/assets/img/icons/allDep.svg" %} alt="allDep.svg"/>
            </div>
            <span class="CategoriesButton-text">{% trans "All categories" %}</span>
            <div class="CategoriesButton-arrow">
            </div>
        </div>
        <div class="CategoriesButton-content">
            {% recursetree object_list %}
                <div class="CategoriesButton-link">
                    <a href={{ node.get_absolute_url }}>
                        <div class="CategoriesButton-icon">
                            <img src={{ node.icon.url }} alt="3.svg"/>
                        </div>
                        <span class="CategoriesButton-text">{{ node.title }}</span>
                    </a>
                    {% if not node.is_leaf_node %}
                        <a class="CategoriesButton-arrow" href="#"></a>
                        <div class="CategoriesButton-submenu">
                            <span class="CategoriesButton-text">{{ children }}</span>
                        </div>
                    {% endif %}
                </div>
            {% endrecursetree %}
        </div>
    </div>
</div>

megano_shop/templates/megano_shop/compare.html
{% extends 'base.html' %}
{% load static %}
{% load compare_tags %}
{% load i18n %}

{% block title %}{% trans "Items comparison" %}{% endblock title %}

{% block content %}

    <div class="Middle Middle_top">
        <div class="Middle-top">
            <div class="wrap">
                <div class="Middle-header">
                    <h1 class="Middle-title">{% trans "Items comparison" %}</h1>
                    <ul class="breadcrumbs Middle-breadcrumbs">
                        <li class="breadcrumbs-item"><a href="index.html">home</a></li>
                        <li class="breadcrumbs-item breadcrumbs-item_current">
                            <span>{% trans "Items comparison" %}</span></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="Section">
            <div class="wrap">
                {% compare_list request.session as list %}
                {% if not list %}
                    <h1 style="text-align: center;">{% trans "insufficient data for comparison" %}</h1>
                {% elif  list|length < 2 %}
                    <h1 style="text-align: center;">{% trans "insufficient data for comparison" %}</h1>
                    {% get_compare_products request.session title_blank=True name_main=True %}
                    {% get_compare_products request.session title_blank=True name_main=False %}
                    {% get_compare_products request.session title_blunk=False name_main=False %}
                {% else %}
                    <article class="Article">
                        <p>{% trans "some sort of Lorem Ipsum dolores est" %}</p>
                    </article>
                    <div class="Compare">
                    <div class="Compare-header">
                        {% csrf_token %}
                        <label class="toggle Compare-checkDifferent">
                            <input type="checkbox" name="differentFeature" value="true" checked="checked"/>
                            <span class="toggle-box"></span>
                            <span class="toggle-text">{% trans "Only characteristics that differ" %}</span>
                        </label>

                    </div>
                    {% get_compare_products request.session title_blank=True name_main=True %}
                    {% get_compare_products request.session title_blank=True name_main=False %}
                    {% get_compare_products request.session title_blank=False name_main=False %}

                {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

megano_shop/templates/megano_shop/get_delivery_info.html
{% extends 'megano_shop/order_base.html' %}
{% load i18n %}

{% block form %}
    <script>
        const menu = document.querySelectorAll('.NavigateProfile > ul > li')
        menu.forEach(item => {
            const element_url = item.children[0].href
            const current_location = window.location.href
            if (element_url === current_location) {
                item.classList.add('menu-item_ACTIVE')
            }
        })
    </script>

    <div class="Order-block Order-block_OPEN" id="step2">
        <header class="Section-header Section-header_sm">
            <h2 class="Section-title">{% trans "Step 2. Delivery options" %}
            </h2>
        </header>

        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
        <div class="form-group">
            {% for radio in form.delivery_type %}
                <div>
                    <label class="toggle" for="{{ radio.id_for_label }}">
                        {{ radio.tag }}
                        <span class="toggle-box"></span>
                        <span class="toggle-text">{{ radio.choice_label }}</span>
                    </label>
                </div>
            {% endfor %}
        </div>
        <div class="form-group">
            <label class="form-label" for="{{ form.city.id_for_label }}">{{ form.city.label }}
            </label>
            {{ form.city }}
            {% if form.city.errors %}
                {% for error in form.city.errors %}
                    <small class="alert-danger d-block">{{ error }}</small>
                {% endfor %}
            {% endif %}
        </div>
        <div class="form-group">
            <label class="form-label" for="{{ form.address.id_for_label }}">{{ form.address.label }}
            </label>
            {{ form.address }}
            {% if form.address.errors %}
                {% for error in form.address.errors %}
                    <small class="alert-danger d-block">{{ error }}</small>
                {% endfor %}
            {% endif %}

        </div>
        <div class="Order-footer">
            <button class="btn btn_success" type="submit">{% trans "Next" %}</button>
        </div>
    </div>

{% endblock form %}

megano_shop/templates/megano_shop/submit_order.html
{% extends 'megano_shop/order_base.html' %}
{% load i18n %}

{% block form %}

    <script>
        const menu = document.querySelectorAll('.NavigateProfile > ul > li')
        menu.forEach(item => {
            const element_url = item.children[0].href
            const current_location = window.location.href
            if (element_url === current_location) {
                item.classList.add('menu-item_ACTIVE')
            }
        })
    </script>
    <div class="Order-block Order-block_OPEN">
        <header class="Section-header Section-header_sm">
            <h2 class="Section-title">{% trans "Step 4. Order confirmation" %}</h2>
        </header>
        <!--+div.Order.-confirmation-->
        {% for order in orders %}

            <div class="Order-infoBlock">
                <div class="Order-personal">
                    <div class="row_">
                        <div class="row-block">
                            <div class="Order-info">
                                <div class="Order-infoType">ФИО:
                                </div>
                                <div class="Order-infoContent">{{ order.buyer.profile.last_name }} {{ order.buyer.profile.first_name }} {{ order.buyer.profile.third_name }}
                                </div>
                            </div>
                            <div class="Order-info">
                                <div class="Order-infoType">{% trans "Phone number:" %}
                                </div>
                                <div class="Order-infoContent">+7{{ order.buyer.profile.phone_number }}
                                </div>
                            </div>
                            <div class="Order-info">
                                <div class="Order-infoType">{% trans "E-mail:" %}
                                </div>
                                <div class="Order-infoContent">{{ order.buyer.email }}
                                </div>
                            </div>
                        </div>
                        <div class="row-block">
                            <div class="Order-info Order-info_delivery">
                                <div class="Order-infoType">{% trans "Delivery option:" %}
                                </div>
                                <div class="Order-infoContent">{{ order.get_shipping_type_display }}
                                </div>
                            </div>
                            <div class="Order-info">
                                <div class="Order-infoType">{% trans "City:" %}
                                </div>
                                <div class="Order-infoContent">{{ order.buyer.profile.city }}
                                </div>
                            </div>
                            <div class="Order-info">
                                <div class="Order-infoType">{% trans "Address:" %}
                                </div>
                                <div class="Order-infoContent">{{ order.buyer.profile.address }}
                                </div>
                            </div>
                            <div class="Order-info Order-info_pay">
                                <div class="Order-infoType">{% trans "Payment:" %}
                                </div>
                                <div class="Order-infoContent">{{ order.get_payment_method_display }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="Cart Cart_order">
                    {% for cart_item in order.cart.all %}

                        <div class="Cart-product">
                            <div class="Cart-block Cart-block_row">
                                <div class="Cart-block Cart-block_pict"><a class="Cart-pict" href="#"><img
                                        class="Cart-img"
                                        src="{{ cart_item.item.main_image.url }}"
                                        alt="card.jpg"/></a>
                                </div>
                                <div class="Cart-block Cart-block_info"><a class="Cart-title"
                                                                           href="#">{{ cart_item.item.title }}</a>
                                    <div class="Cart-desc">{{ cart_item.item.description|truncatechars:250 }}
                                    </div>
                                </div>
                                <div class="Cart-block Cart-block_price">
                                    <div class="Cart-price">{{ cart_item.total_price }}&#8381;
                                    </div>
                                </div>
                            </div>
                            <div class="Cart-block Cart-block_row">
                                <div class="Cart-block Cart-block_amount">{{ cart_item.items_qty }}{% trans "pcs" %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    <div class="Cart-total">
                        <div class="Cart-block Cart-block_total">
                            <strong class="Cart-title">{% trans "Total:" %}
                            </strong><span class="Cart-price">{{ order.calculate_price_with_ship }}&#8381;</span>
                        </div>
                        <div class="Cart-block">
                            <a href="{% url "get_payment_data" order.order_number %}"
                               class="btn btn_primary btn_lg"
                               type="submit">{% trans "Pay" %}
                            </a>
                        </div>
                    </div>
                </div>
            </div>



        {% endfor %}
    </div>
{% endblock form %}