cart/urls.py
from django.urls import path

from .views import CartSummary, UpdateCart, UsePromoCode

urlpatterns = [
    path("", CartSummary.as_view(), name="cart_summary"),
    path("update-cart/", UpdateCart.as_view(), name="cart_update"),
    path("use-promo-code/", UsePromoCode.as_view(), name="use_promo_code"),
]

python_django_team17/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("acc/", include("account.urls")),
    path("", include("megano_shop.urls")),
    path("payment/", include("payment.urls")),
    path("cart/", include("cart.urls")),
    path("i18n", include("django.conf.urls.i18n")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

megano_shop/models.py
from decimal import Decimal

from constance import config
from django.contrib import admin
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    """Model for Category with nasted tree"""

    title = models.CharField(max_length=60, unique=True, verbose_name=_("Category"))
    parent = TreeForeignKey(
        "self",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="children",
        verbose_name=_("Parent category"),
    )
    slug = models.SlugField()
    is_active = models.BooleanField(verbose_name=_("Is active"), default=False)
    icon = models.ImageField(
        upload_to="img/category_icons", verbose_name=_("Icon"), blank=True, null=True
    )
    discount = models.ManyToManyField(
        to="Discounts", blank=True, verbose_name=_("Discount")
    )

    class MPTTMeta:
        order_insertion_by = ["title"]

    class Meta:
        unique_together = [["parent", "slug"]]
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    @admin.display(description="Icon_preview")
    def icon_prev(self):
        return mark_safe(f'<img src="{self.icon.url}" width="100"/>')

    def get_absolute_url(self):
        return reverse("filtered_category", kwargs={"path": self.get_path()})

    def __str__(self):
        return self.title


class Tags(models.Model):
    name = models.CharField(max_length=50, verbose_name=_("Tag"))

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")

    def __str__(self):
        return self.name


class Images(models.Model):
    image = models.ImageField(upload_to="items", blank=True, verbose_name=_("Image"))

    class Meta:
        verbose_name = _("Image")
        verbose_name_plural = _("Images")


class Item(models.Model):
    """Model for Item"""

    STATUS_CHOICES = [
        ("a", "Active"),
        ("i", "Inactive"),
    ]

    category = TreeForeignKey(
        Category,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="item_category",
        verbose_name=_("Category"),
    )
    slug = models.SlugField(verbose_name=_("slug"))
    tag = models.ManyToManyField(
        Tags, blank=True, related_name="tag_item", verbose_name=_("Tag")
    )
    title = models.CharField(max_length=100, verbose_name=_("Title"))
    main_image = models.ImageField(
        upload_to="img/item_images/%Y/%m/%d/", blank=True, verbose_name=_("Main image")
    )
    discount = models.ManyToManyField(
        "Discounts", blank=True, related_name="item", verbose_name=_("Discount")
    )
    images = models.ManyToManyField(Images, blank=True, verbose_name=_("Images"))
    description = models.TextField(max_length=1000, verbose_name=_("Description"))
    status = models.CharField(
        max_length=1, choices=STATUS_CHOICES, default="a", verbose_name=_("Status")
    )
    specifications = models.JSONField(
        verbose_name=_("Specifications"), blank=True, null=True
    )
    count_view = models.IntegerField(default=0, verbose_name=_("count view"))

    class Meta:
        verbose_name = _("Item")
        verbose_name_plural = _("Items")

    def get_absolute_url(self):
        return reverse("items_list", args=[str(self.slug)])

    def __str__(self):
        return self.title

    def __repr__(self):
        return self.title


class Banner(models.Model):
    """Model for Banners"""

    image = models.ImageField(
        upload_to="images/%Y/%m/%d/", blank=True, verbose_name=_("Banner image")
    )
    link = models.URLField(max_length=200, verbose_name=_("URL"))
    title = models.CharField(max_length=17, verbose_name=_("Title"))
    description = models.TextField(max_length=300, verbose_name=_("Description"))
    is_active = models.BooleanField(default=False, verbose_name=_("Status"))

    class Meta:
        # verbose_name = "Banner"
        verbose_name_plural = _("Banners")

    def get_absolute_url(self):
        pass

    def __str__(self):
        return self.link


class Reviews(models.Model):
    """Reviews model"""

    created_on = models.DateTimeField(
        auto_now_add=True, verbose_name=_("Creation date")
    )
    edited_on = models.DateTimeField(auto_now=True, verbose_name=_("Updating date"))
    user = models.ForeignKey(
        to=User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        verbose_name=_("User"),
        related_name="review_user",
    )
    item = models.ForeignKey(
        to=Item,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        verbose_name=_("Item"),
        related_name="review_item",
    )
    content = models.TextField(
        max_length=3000, blank=True, verbose_name=_("Review text")
    )

    class Meta:
        verbose_name = _("Review")
        verbose_name_plural = _("Reviews")

    def __str__(self):
        if User.is_authenticated:
            return str(self.user)
        else:
            return _("Guest")


class Discounts(models.Model):
    """Model for Discount"""

    TYPE = [
        ("p", _("Promo code")),
        ("d", _("Discount")),
    ]

    AMOUNT_CHOICE = [("cashed", _("Fixed amount")), ("percentage", _("Percentage"))]

    title = models.CharField(max_length=200, verbose_name=_("Title"))
    description = models.TextField(verbose_name=_("Description"))
    image = models.ImageField(
        upload_to="images/%Y/%m/%d/promo/", blank=True, verbose_name=_("Promo image")
    )
    discount_weight = models.PositiveIntegerField(
        default=0,
        validators=[MaxValueValidator(10), MinValueValidator(1)],
        verbose_name=_("Discount weight"),
    )
    discount_type = models.CharField(
        max_length=1, choices=TYPE, default="d", verbose_name=_("Discount type")
    )
    amount_type = models.CharField(
        max_length=10,
        choices=AMOUNT_CHOICE,
        default="cashed",
        verbose_name=_("Amount type"),
    )
    amount = models.PositiveIntegerField(
        default=0, verbose_name=_("Discount"), blank=True, null=True
    )
    promo_code = models.CharField(
        max_length=50, verbose_name=_("Promo code text"), blank=True, null=True
    )
    items_qty = models.PositiveIntegerField(
        default=0, validators=[MaxValueValidator(100), MinValueValidator(0)]
    )
    starts_on = models.DateTimeField(blank=True, verbose_name=_("Starts on"), null=True)
    ends_on = models.DateTimeField(blank=True, verbose_name=_("Ends on"), null=True)
    is_active = models.BooleanField(default=False, verbose_name=_("Activity"))

    class Meta:
        verbose_name = _("Discount")
        verbose_name_plural = _("Discounts")

    def __str__(self):
        return self.title


class AppliedDiscounts(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        verbose_name=_("User"),
        related_name="user_applied_discount",
    )
    discount = models.ForeignKey(
        to=Discounts,
        on_delete=models.CASCADE,
        verbose_name=_("Discount"),
        related_name="applied_discount",
    )

    class Meta:
        db_table = "megano_shop_applied_discounts"
        verbose_name = _("Applied Discount")
        verbose_name_plural = _("Applied Discounts")


class Stock(models.Model):
    """Model for Stock"""

    item = models.ForeignKey(
        Item,
        blank=True,
        on_delete=models.CASCADE,
        related_name="stock_item",
        verbose_name=_("Item"),
    )
    seller = models.ForeignKey(
        User, blank=True, on_delete=models.PROTECT, verbose_name=_("Seller")
    )
    quantity = models.PositiveIntegerField(default=0, verbose_name=_("Quantity"))
    discount = models.ForeignKey(
        Discounts,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_("Discount"),
    )
    price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0, verbose_name=_("Price")
    )
    count_view = models.IntegerField(default=0, verbose_name=_("count view"))
    created_on = models.DateTimeField(auto_now_add=True, verbose_name=_("Created on"))

    class Meta:
        verbose_name = _("Stock")
        verbose_name_plural = _("Stocks")

    def __str__(self):
        return self.seller.username

    @property
    def get_category(self):
        return self.item.category


class Order(models.Model):
    ORDER_STATUS_CHOICES = [
        ("o", _("Open")),
        ("c", _("Closed")),
    ]
    PAYMENT_STATUS_CHOICES = [
        ("p", _("Payed")),
        ("u", _("Not paid")),
    ]
    DELIVERY_CHOICE = (
        ("ordinary", _("Ordinary delivery")),
        ("express", _("Express delivery")),
    )
    PAYMENT_CHOICE = (
        ("online_card", _("Online")),
        ("online_account", _("Online from random person's account")),
    )
    order_number = models.CharField(
        max_length=6, unique=True, verbose_name=_("Order number")
    )
    buyer = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name="order_buyer",
        verbose_name=_("Customer"),
    )
    total_price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0, verbose_name=_("Total amount")
    )
    payment_method = models.CharField(
        max_length=60,
        choices=PAYMENT_CHOICE,
        default="online_card",
        verbose_name=_("Payment method"),
    )
    shipping_type = models.CharField(
        max_length=250,
        choices=DELIVERY_CHOICE,
        default="ordinary",
        verbose_name=_("Delivery"),
    )
    payment_status = models.CharField(
        max_length=60,
        choices=PAYMENT_STATUS_CHOICES,
        default="u",

templates/base_form.html
{% load static %}

<!DOCTYPE html>

<html lang="ru">


<head>
    <meta name="description" content="Описание страницы">
    <meta charset="utf-8">

    <title>
        {% block title %}{% endblock title %}
    </title>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">

    <link href="{% static "assets/img/favicon.ico" %}" rel="shortcut icon">
    <link rel="preload" href={% static "assets/fonts/Roboto/Roboto-Regular.woff" %} as="font">
    <link rel="preload" href={% static "assets/fonts/Roboto/Roboto-Italic.woff" %} as="font">
    <link rel="preload" href={% static "assets/fonts/Roboto/Roboto-Bold.woff" %} as="font">
    <link rel="preload" href={% static "assets/fonts/Roboto/Roboto-Bold_Italic.woff" %} as="font">
    <link rel="preload" href={% static "assets/fonts/Roboto/Roboto-Light.woff" %} as="font">
    <link rel="preload" href={% static "assets/fonts/Roboto/Roboto-Light_Italic.woff" %} as="font">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href={% static "assets/css/fonts.css" %}>
    <link rel="stylesheet" href={% static "assets/css/basic.css" %}>
    <link rel="stylesheet" href={% static "assets/css/extra.css" %}>
    <script src={% static "assets/plg/CountDown/countdown.js" %}></script>
    {#    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>#}
</head>


<body>

{% block header %}
    {% include 'header_form.html' %}
{% endblock header %}


{% block content %}
{% endblock content %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock footer %}



<script src={% static "assets/plg/jQuery/jquery-3.5.0.slim.min.js" %}></script>
<script src={% static "assets/plg/form/jquery.form.js" %}></script>
<script src={% static "assets/plg/form/jquery.maskedinput.min.js" %}></script>
<script src={% static "assets/plg/range/ion.rangeSlider.min.js" %}></script>
<script src={% static "assets/plg/Slider/slick.min.js" %}></script>
<script src={% static "assets/js/scripts.js" %}></script>
</body>

templates/e-mail.html
{% extends 'base_form.html' %}

{% block title %}Password recovery{% endblock title %}
{% load static %}
{% block content %}
    <div class="wrap">
        <div class="row_ Header-rowMain">
            <div class="row-block Header-logo"><a class="logo" href="index.html"><img class="logo-image"
                                                                                      src={% static "assets/img/logo.png" %} alt="logo.png"/></a>
            </div>
        </div>


        <div class="wrapper">
            <div class="header">
                <h3 class="sign-in">Восстановление пароля (1/2)</h3>
                <h5>Для восстановления пароля введите адрес электронной почты, на которую зарегистрирована учетная
                    запись</h5>
            </div>

            {% if messages %}
               {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            {% endif %}

            <form method="post">

                {% csrf_token %}
                {{ form.as_p }}
                <div>
                    <input type="submit" value="Получить проверочный код"/>
                </div>
                <a class="registr" href="{% url 'login' %}">
                    Вход
                </a>
            </form>
        </div>

    </div>

{% endblock content %}

templates/footer.html
{% load static %}
{% load i18n %}

{% block footer %}
    <footer class="Footer">
        <div class="wrap">
            <div class="row Footer-main">
                <div class="row-block"><a class="logo Footer-logo" href="index.html"><img class="logo-image"
                                                                                          src="{% static 'assets/img/logo_footer.png' %}"
                                                                                          alt="logo_footer.png"/></a>
                </div>
                <div class="row-block">
                    <strong class="Footer-title">{% trans "Navigation" %}
                    </strong>
                    <ul class="menu menu_vt Footer-menu">
                        <li class="menu-item"><a class="menu-link" href="{% url "index" %}">{% trans "Main" %}</a>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="catalog.html">{% trans "Catalogue" %}</a>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="comparison.html">{% trans "Comparison" %}</a>
                        </li>
                        {% if request.user.is_authenticated %}
                        <li class="menu-item"><a class="menu-link" href="{% url 'account' request.user.username %} ">{% trans "Profile" %}</a>
                        </li>
                        {% endif %}

                    </ul>
                </div>
                <div class="row-block">
                    <strong class="Footer-title">{% trans "Contacts" %}
                    </strong>
                    <p>{% trans "Phone:" %} 8.800.200.600<br>{% trans "Email:" %} xxx@meg.com<br>
                    </p>
                    <ul class="menu menu_img menu_smallImg Footer-menuSoc">
                        <li class="menu-item"><a class="menu-link" href="#"><img
                                src={% static "assets/img/icons/socialHeader/tw.svg" %} alt="tw.svg"/></a>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="#"><img
                                src={% static "assets/img/icons/socialHeader/in.svg" %} alt="in.svg"/></a>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="#"><img
                                src={% static "assets/img/icons/socialHeader/pt.svg" %} alt="pt.svg"/></a>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="#"><img
                                src={% static "assets/img/icons/socialHeader/mail.svg" %} alt="mail.svg"/></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

{% endblock footer %}

templates/historyorder.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}Orders{% endblock title %}

{% block content %}

    <div class="Middle Middle_top">
        <div class="Middle-top">
            <div class="wrap">
                <div class="Middle-header">
                    <h1 class="Middle-title">{% trans "Orders history" %}
                    </h1>
                    <ul class="breadcrumbs Middle-breadcrumbs">
                        <li class="breadcrumbs-item"><a href="{% url 'index' %}">{% trans "Home" %}</a>
                        </li>
                        <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% trans "Orders history" %}</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="Section Section_column Section_columnLeft">
            <div class="wrap">
                {% block navigation %}
                    {% include 'navigation.html' %}
                {% endblock navigation %}
            </div>
            <div class="Section-content">
                <div class="Orders">
                    {% for order in orders %}
                        <div class="Order Order_anons">
                            <div class="Order-personal">
                                <div class="row_">
                                    <div class="row-block"><a class="Order-title"
                                                              href="/order/{{ order.id }}">{% trans "Order" %}&#32;<span
                                            class="Order-numberOrder">№ {{ order.order_number }}</span>&#32;от&#32;<span
                                            class="Order-dateOrder">{{ order.updated_at }}</span></a>
                                    </div>
                                    <div class="row-block">
                                        <div class="Order-info Order-info_delivery">
                                            <div class="Order-infoType">{% trans "Shipping type" %}:
                                            </div>
                                            <div class="Order-infoContent">{{ order.shipping_type }}
                                            </div>
                                        </div>
                                        <div class="Order-info Order-info_pay">
                                            <div class="Order-infoType">{% trans "Payment method" %}:
                                            </div>
                                            <div class="Order-infoContent">{{ order.payment_method }}
                                            </div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">{% trans "Total price" %}:
                                            </div>
                                            <div class="Order-infoContent"><span
                                                    class="Order-price">{{ order.calculate_price_with_ship }}</span><span
                                                    class="Order-price_old"></span>
                                            </div>
                                        </div>
                                        <div class="Order-info Order-info_status">
                                            <div class="Order-infoType">{% trans "Order status" %}:
                                            </div>
                                            <div class="Order-infoContent">{{ order.get_payment_status_display }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock content %}

templates/message_to_the_mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div style="background-color: #f3f4f9;">
    <div style="font-size: 30px;">
        <p>Hello {{ first_name }} {{ last_name }}</p>
    </div>
    <div style="font-size: 20px;">
        <p>To change your password, follow the <a
                href="http://localhost:8000/acc/password-reset/confirm/{{ uidb }}/{{ token }}">link</a></p>
    </div>
</div>

</body>
</html>

templates/oneorder.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}

{% block content %}

    <div class="Middle Middle_top">
        <div class="Middle-top">
            <div class="wrap">
                <div class="Middle-header">
                    <h1 class="Middle-title">Заказ № {{ order.order_number }}
                    </h1>
                    <ul class="breadcrumbs Middle-breadcrumbs">
                        <li class="breadcrumbs-item"><a href="/">home</a>
                        </li>
                        <li class="breadcrumbs-item"><a href="/acc/account/{{ request.user.username }}/orders">История
                            заказов</a>
                        </li>
                        <li class="breadcrumbs-item breadcrumbs-item_current">
                            <span>Заказ № {{ order.order_number }}</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="Section">
            <div class="wrap">
                <div class="Section-content">
                    <div class="Orders">
                    </div>
                    <div class="Order">
                        <div class="Order-infoBlock">
                            <div class="Order-personal">
                                <div class="row_">
                                    <div class="row-block">
                                        <div class="Order-info Order-info_date">
                                            <div class="Order-infoType">Дата заказа:
                                            </div>
                                            <div class="Order-infoContent">{{ order.updated_at }}
                                            </div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">ФИО:
                                            </div>
                                            <div class="Order-infoContent">{{ order.buyer.profile.last_name }} {{ order.buyer.profile.first_name }} {{ order.buyer.profile.third_name }}
                                            </div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">Телефон:
                                            </div>
                                            <div class="Order-infoContent">{{ order.buyer.profile.phone_number }}
                                            </div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">E-mail:
                                            </div>
                                            <div class="Order-infoContent">{{ order.buyer.email }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row-block">
                                        <div class="Order-info Order-info_delivery">
                                            <div class="Order-infoType">Тип доставки:
                                            </div>
                                            <div class="Order-infoContent">{{ order.shipping_type }}
                                            </div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">Город:
                                            </div>
                                            <div class="Order-infoContent">{{ order.buyer.profile.city }}
                                            </div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">Адрес:
                                            </div>
                                            <div class="Order-infoContent">{{ order.buyer.profile.address }}
                                            </div>
                                        </div>
                                        <div class="Order-info Order-info_pay">
                                            <div class="Order-infoType">Оплата:
                                            </div>
                                            <div class="Order-infoContent">{{ order.payment_method }}
                                            </div>
                                        </div>
                                        <div class="Order-info Order-info_status">
                                            <div class="Order-infoType">Статус:
                                            </div>
                                            <div class="Order-infoContent">{{ order.get_payment_status_display }}
                                            </div>
                                        </div>
                                        {% if order.payment_status == 'u' %}
                                            <div class="Order-info Order-info_error">
                                                <div class="Order-infoType">Оплата не прошла:
                                                </div>
                                                <div class="Order-infoContent">Заказ не оплачен
                                                </div>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="Cart Cart_order">
                                {% for good in goods %}
                                    <div class="Cart-product">
                                        <div class="Cart-block Cart-block_row">
                                            <div class="Cart-block Cart-block_pict"><a class="Cart-pict"
                                                                                       href="{% url 'product_detail' good.item.id %}"><img
                                                    class="Cart-img" src="../media/{{ good.item.main_image }}"
                                                    alt="{{ good.item }}"/></a>
                                            </div>
                                            <div class="Cart-block Cart-block_info"><a class="Cart-title"
                                                                                       href="{% url 'product_detail' good.item.id %}">{{ good.item.category }}</a>
                                                <div class="Cart-desc">{{ good.item.description }}
                                                </div>
                                            </div>
                                            <div class="Cart-block Cart-block_price">
                                                <div class="Cart-price">{{ good.item.price }}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="Cart-block Cart-block_row">
                                            <div class="Cart-block Cart-block_seller">
                                                <div>Продавец:
                                                </div>
                                                <div>{{ good.stock }}
                                                </div>
                                            </div>
                                            <div class="Cart-block Cart-block_amount">{{ good.items_qty }} шт.
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                                <div class="Cart-total">
                                    <div class="Cart-block Cart-block_total">
                                        <strong class="Cart-title">Итого:<span
                                                class="Cart-price">{{ order.total_price }}</span><span
                                                class="Cart-price_old"></span>
                                        </strong>
                                    </div>
                                    {% if order.payment_status == 'u' %}
                                        <div class="Cart-block"><a class="btn btn_primary btn_lg" onclick="show_loader()" href="{% url 'proceed_payment' %}">Оплатить</a>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
 <script>

        function show_loader() {
            const spinner = document.getElementById('spinner')
            const payment = document.getElementById('payment')

            payment.style.display = 'none'
            spinner.style.display = 'block'
        }

    </script>
{% endblock content %}